url: "http://cathydutton.co.uk"
baseurl: ""

# Site settings
environment: live
title: Cheshire based Interaction Designer &amp; Front End Developer - Cathy Dutton
description: A UX/Interaction Designer and Front End Developer based in Warrington, Cheshire. Specialising in CSS, UX, Accessibility and inclusive design.
email: info@cathydutton.co.uk

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/cathy_dutton



# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /posts/:title.html

# Plugins
gems:
  - jekyll-sitemap

collections:
  portfolio:
    output: true
    permalink: /portfolio/:title.html


exclude: ["node_modules", "default.yml", "gulpfile.js", "LICENSE.txt", "package.json", "README.md", "scssReport.json", "stats", "tasks"]
